// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForBulkCreateReservationTickets implements pgx.CopyFromSource.
type iteratorForBulkCreateReservationTickets struct {
	rows                 []BulkCreateReservationTicketsParams
	skippedFirstNextCall bool
}

func (r *iteratorForBulkCreateReservationTickets) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForBulkCreateReservationTickets) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ReservationID,
		r.rows[0].TicketID,
	}, nil
}

func (r iteratorForBulkCreateReservationTickets) Err() error {
	return nil
}

func (q *Queries) BulkCreateReservationTickets(ctx context.Context, arg []BulkCreateReservationTicketsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"reservationticket"}, []string{"reservation_id", "ticket_id"}, &iteratorForBulkCreateReservationTickets{rows: arg})
}
