// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Reservation struct {
	ID        pgtype.UUID        `json:"id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	UserID    pgtype.UUID        `json:"user_id"`
	EventID   pgtype.UUID        `json:"event_id"`
	Status    string             `json:"status"`
}

type Reservationticket struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	TicketID      pgtype.UUID `json:"ticket_id"`
}

type Ticket struct {
	ID            pgtype.UUID        `json:"id"`
	ReservationID pgtype.UUID        `json:"reservation_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	ZoneNumber    int32              `json:"zone_number"`
	RowNumber     int32              `json:"row_number"`
	ColNumber     int32              `json:"col_number"`
}
