// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BulkCreateReservationTickets(ctx context.Context, arg []BulkCreateReservationTicketsParams) (int64, error)
	CheckReservationTicketExists(ctx context.Context, arg CheckReservationTicketExistsParams) (bool, error)
	CheckSeatAvailability(ctx context.Context, arg CheckSeatAvailabilityParams) (bool, error)
	CheckSeatAvailabilityForEvent(ctx context.Context, arg CheckSeatAvailabilityForEventParams) (bool, error)
	CountReservationsByEventID(ctx context.Context, eventID pgtype.UUID) (int64, error)
	CountReservationsByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountReservationsForTicket(ctx context.Context, ticketID pgtype.UUID) (int64, error)
	CountTicketsByReservationID(ctx context.Context, reservationID pgtype.UUID) (int64, error)
	CountTicketsInReservation(ctx context.Context, reservationID pgtype.UUID) (int64, error)
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	CreateReservationTicket(ctx context.Context, arg CreateReservationTicketParams) error
	CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error)
	CreateTicketWithAvailabilityCheck(ctx context.Context, arg CreateTicketWithAvailabilityCheckParams) (Ticket, error)
	DeleteReservation(ctx context.Context, id pgtype.UUID) error
	DeleteReservationTicket(ctx context.Context, arg DeleteReservationTicketParams) error
	DeleteReservationTicketsByReservationID(ctx context.Context, reservationID pgtype.UUID) error
	DeleteReservationTicketsByTicketID(ctx context.Context, ticketID pgtype.UUID) error
	DeleteTicket(ctx context.Context, id pgtype.UUID) error
	DeleteTicketsByReservationID(ctx context.Context, reservationID pgtype.UUID) error
	GetReservation(ctx context.Context, id pgtype.UUID) (Reservation, error)
	GetReservationByID(ctx context.Context, id pgtype.UUID) (Reservation, error)
	GetReservationByStripeSessionID(ctx context.Context, stripeSessionID string) (Reservation, error)
	GetReservationTickets(ctx context.Context, reservationID pgtype.UUID) ([]GetReservationTicketsRow, error)
	GetTicket(ctx context.Context, id pgtype.UUID) (Ticket, error)
	GetTicketByID(ctx context.Context, id pgtype.UUID) (Ticket, error)
	GetTicketBySeat(ctx context.Context, arg GetTicketBySeatParams) (Ticket, error)
	GetTicketReservations(ctx context.Context, ticketID pgtype.UUID) ([]GetTicketReservationsRow, error)
	HardDeleteReservation(ctx context.Context, id pgtype.UUID) error
	HardDeleteTicket(ctx context.Context, id pgtype.UUID) error
	ListAllReservationTickets(ctx context.Context) ([]Reservationticket, error)
	ListReservations(ctx context.Context) ([]Reservation, error)
	ListReservationsByEventID(ctx context.Context, eventID pgtype.UUID) ([]Reservation, error)
	ListReservationsByStatus(ctx context.Context, status string) ([]Reservation, error)
	ListReservationsByUserID(ctx context.Context, userID pgtype.UUID) ([]Reservation, error)
	ListTickets(ctx context.Context) ([]Ticket, error)
	ListTicketsByReservationID(ctx context.Context, reservationID pgtype.UUID) ([]Ticket, error)
	ListTicketsBySeat(ctx context.Context, arg ListTicketsBySeatParams) ([]Ticket, error)
	UpdateReservation(ctx context.Context, arg UpdateReservationParams) (Reservation, error)
	UpdateReservationStatus(ctx context.Context, arg UpdateReservationStatusParams) (Reservation, error)
	UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error)
	UpdateTicketReservation(ctx context.Context, arg UpdateTicketReservationParams) (Ticket, error)
}

var _ Querier = (*Queries)(nil)
