// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reservation_ticket.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type BulkCreateReservationTicketsParams struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	TicketID      pgtype.UUID `json:"ticket_id"`
}

const checkReservationTicketExists = `-- name: CheckReservationTicketExists :one
SELECT EXISTS(
    SELECT 1 FROM ReservationTicket
    WHERE reservation_id = $1 AND ticket_id = $2
) AS exists
`

type CheckReservationTicketExistsParams struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	TicketID      pgtype.UUID `json:"ticket_id"`
}

func (q *Queries) CheckReservationTicketExists(ctx context.Context, arg CheckReservationTicketExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkReservationTicketExists, arg.ReservationID, arg.TicketID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countReservationsForTicket = `-- name: CountReservationsForTicket :one
SELECT COUNT(*) FROM ReservationTicket
WHERE ticket_id = $1
`

func (q *Queries) CountReservationsForTicket(ctx context.Context, ticketID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countReservationsForTicket, ticketID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTicketsInReservation = `-- name: CountTicketsInReservation :one
SELECT COUNT(*) FROM ReservationTicket
WHERE reservation_id = $1
`

func (q *Queries) CountTicketsInReservation(ctx context.Context, reservationID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTicketsInReservation, reservationID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReservationTicket = `-- name: CreateReservationTicket :exec
INSERT INTO ReservationTicket (
    reservation_id,
    ticket_id
) VALUES (
    $1, $2
)
`

type CreateReservationTicketParams struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	TicketID      pgtype.UUID `json:"ticket_id"`
}

func (q *Queries) CreateReservationTicket(ctx context.Context, arg CreateReservationTicketParams) error {
	_, err := q.db.Exec(ctx, createReservationTicket, arg.ReservationID, arg.TicketID)
	return err
}

const deleteReservationTicket = `-- name: DeleteReservationTicket :exec
DELETE FROM ReservationTicket
WHERE reservation_id = $1 AND ticket_id = $2
`

type DeleteReservationTicketParams struct {
	ReservationID pgtype.UUID `json:"reservation_id"`
	TicketID      pgtype.UUID `json:"ticket_id"`
}

func (q *Queries) DeleteReservationTicket(ctx context.Context, arg DeleteReservationTicketParams) error {
	_, err := q.db.Exec(ctx, deleteReservationTicket, arg.ReservationID, arg.TicketID)
	return err
}

const deleteReservationTicketsByReservationID = `-- name: DeleteReservationTicketsByReservationID :exec
DELETE FROM ReservationTicket
WHERE reservation_id = $1
`

func (q *Queries) DeleteReservationTicketsByReservationID(ctx context.Context, reservationID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReservationTicketsByReservationID, reservationID)
	return err
}

const deleteReservationTicketsByTicketID = `-- name: DeleteReservationTicketsByTicketID :exec
DELETE FROM ReservationTicket
WHERE ticket_id = $1
`

func (q *Queries) DeleteReservationTicketsByTicketID(ctx context.Context, ticketID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReservationTicketsByTicketID, ticketID)
	return err
}

const getReservationTickets = `-- name: GetReservationTickets :many
SELECT
    rt.reservation_id,
    rt.ticket_id,
    t.id, t.reservation_id, t.created_at, t.updated_at, t.deleted_at, t.zone_number, t.row_number, t.col_number
FROM ReservationTicket rt
JOIN Ticket t ON rt.ticket_id = t.id
WHERE rt.reservation_id = $1 AND t.deleted_at IS NULL
`

type GetReservationTicketsRow struct {
	ReservationID   pgtype.UUID        `json:"reservation_id"`
	TicketID        pgtype.UUID        `json:"ticket_id"`
	ID              pgtype.UUID        `json:"id"`
	ReservationID_2 pgtype.UUID        `json:"reservation_id_2"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	ZoneNumber      int32              `json:"zone_number"`
	RowNumber       int32              `json:"row_number"`
	ColNumber       int32              `json:"col_number"`
}

func (q *Queries) GetReservationTickets(ctx context.Context, reservationID pgtype.UUID) ([]GetReservationTicketsRow, error) {
	rows, err := q.db.Query(ctx, getReservationTickets, reservationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetReservationTicketsRow{}
	for rows.Next() {
		var i GetReservationTicketsRow
		if err := rows.Scan(
			&i.ReservationID,
			&i.TicketID,
			&i.ID,
			&i.ReservationID_2,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ZoneNumber,
			&i.RowNumber,
			&i.ColNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketReservations = `-- name: GetTicketReservations :many
SELECT
    rt.reservation_id,
    rt.ticket_id,
    r.id, r.created_at, r.updated_at, r.deleted_at, r.user_id, r.event_id, r.status
FROM ReservationTicket rt
JOIN Reservation r ON rt.reservation_id = r.id
WHERE rt.ticket_id = $1 AND r.deleted_at IS NULL
`

type GetTicketReservationsRow struct {
	ReservationID pgtype.UUID        `json:"reservation_id"`
	TicketID      pgtype.UUID        `json:"ticket_id"`
	ID            pgtype.UUID        `json:"id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
	UserID        pgtype.UUID        `json:"user_id"`
	EventID       pgtype.UUID        `json:"event_id"`
	Status        string             `json:"status"`
}

func (q *Queries) GetTicketReservations(ctx context.Context, ticketID pgtype.UUID) ([]GetTicketReservationsRow, error) {
	rows, err := q.db.Query(ctx, getTicketReservations, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetTicketReservationsRow{}
	for rows.Next() {
		var i GetTicketReservationsRow
		if err := rows.Scan(
			&i.ReservationID,
			&i.TicketID,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UserID,
			&i.EventID,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllReservationTickets = `-- name: ListAllReservationTickets :many
SELECT reservation_id, ticket_id FROM ReservationTicket
`

func (q *Queries) ListAllReservationTickets(ctx context.Context) ([]Reservationticket, error) {
	rows, err := q.db.Query(ctx, listAllReservationTickets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservationticket{}
	for rows.Next() {
		var i Reservationticket
		if err := rows.Scan(&i.ReservationID, &i.TicketID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
