---
# Location MongoDB
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-mongo-config
  namespace: aconcert
data:
  MONGO_INITDB_ROOT_USERNAME: "root"
  MONGO_INITDB_ROOT_PASSWORD: "password"
  MONGO_INITDB_DATABASE: "aconcert"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: location-mongo-pvc
  namespace: aconcert
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-mongo
  namespace: aconcert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-mongo
  template:
    metadata:
      labels:
        app: location-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6.0
        envFrom:
        - configMapRef:
            name: location-mongo-config
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: location-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: location-mongo
  namespace: aconcert
spec:
  selector:
    app: location-mongo
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
