---
apiVersion: v1
kind: ConfigMap
metadata:
  name: location-service-config
  namespace: aconcert
data:
  NAME: "aconcert-location-service"
  PORT: "8000"
  ENVIRONMENT: "production"
  LOGGER_LEVEL: "info"
  LOGGER_FORMAT: "json"
  MONGO_DATABASE: "aconcert"
  MONGO_USERNAME: "root"
  MONGO_PASSWORD: "password"
  MONGO_PORT: "27017"
  MONGO_HOST: "location-mongo.aconcert.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
  namespace: aconcert
  labels:
    app: location-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: aconcert/location-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: grpc
          envFrom:
            - configMapRef:
                name: location-service-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            grpc:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            grpc:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 3
            failureThreshold: 2
      initContainers:
        - name: wait-for-mongo
          image: busybox:1.35
          command:
            [
              "sh",
              "-c",
              "until nc -z location-mongo.aconcert.svc.cluster.local 27017; do echo waiting for mongo; sleep 2; done;",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: location-service
  namespace: aconcert
spec:
  selector:
    app: location-service
  ports:
    - port: 8000
      targetPort: 8000
      name: grpc
  type: ClusterIP
