---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
  namespace: aconcert
data:
  NAME: "aconcert-payment-service"
  PORT: "8000"
  ENVIRONMENT: "production"
  MAX_BODY_LIMIT: "10485760"
  LOGGER_LEVEL: "info"
  LOGGER_FORMAT: "json"
  STRIPE_SECRET_KEY: "sk_test_your_stripe_key"
  RESERVATION_CLIENT_BASE_URL: "http://reservation-service.aconcert.svc.cluster.local:8000"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: aconcert
  labels:
    app: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: aconcert/payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: payment-service-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            httpGet:
              path: /livez
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: aconcert
spec:
  selector:
    app: payment-service
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
