---
apiVersion: v1
kind: ConfigMap
metadata:
  name: reservation-service-config
  namespace: aconcert
data:
  NAME: "aconcert-reservation-service"
  PORT: "8000"
  ENVIRONMENT: "production"
  LOGGER_LEVEL: "info"
  LOGGER_FORMAT: "json"
  POSTGRES_HOST: "reservation-postgres.aconcert.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  POSTGRES_DB: "reservation"
  REDIS_URL: "redis://reservation-redis.aconcert.svc.cluster.local:6379"
  STRIPE_SECRET_KEY: "sk_test_your_stripe_key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation-service
  namespace: aconcert
  labels:
    app: reservation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation-service
  template:
    metadata:
      labels:
        app: reservation-service
    spec:
      containers:
        - name: reservation-service
          image: aconcert/reservation-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: grpc
          envFrom:
            - configMapRef:
                name: reservation-service-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          livenessProbe:
            grpc:
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 120
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            grpc:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 120
            timeoutSeconds: 3
            failureThreshold: 2
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command:
            [
              "sh",
              "-c",
              "until nc -z reservation-postgres.aconcert.svc.cluster.local 5432; do echo waiting for postgres; sleep 2; done;",
            ]
        - name: wait-for-redis
          image: busybox:1.35
          command:
            [
              "sh",
              "-c",
              "until nc -z reservation-redis.aconcert.svc.cluster.local 6379; do echo waiting for redis; sleep 2; done;",
            ]
---
apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: aconcert
spec:
  selector:
    app: reservation-service
  ports:
    - port: 8000
      targetPort: 8000
      name: grpc
  type: ClusterIP
