// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Insert a new user
	CreateUser(ctx context.Context, arg CreateUserParams) (pgtype.UUID, error)
	// Soft delete a user
	DeleteUser(ctx context.Context, id pgtype.UUID) (interface{}, error)
	// Get a user by email
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Get a single user by ID
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// Hard delete a user (for admin use)
	HardDeleteUser(ctx context.Context, id pgtype.UUID) (interface{}, error)
	// List all users
	ListUsers(ctx context.Context) ([]User, error)
	// Update an existing user
	UpdateUser(ctx context.Context, arg UpdateUserParams) (interface{}, error)
}

var _ Querier = (*Queries)(nil)
