// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: reservation/reservation.proto

package reservationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------ Messages ------------------ //
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_reservation_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{0}
}

type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneNumber    int32                  `protobuf:"varint,1,opt,name=zone_number,json=zoneNumber,proto3" json:"zone_number,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Row           int32                  `protobuf:"varint,4,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,5,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_reservation_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *Seat) GetZoneNumber() int32 {
	if x != nil {
		return x.ZoneNumber
	}
	return 0
}

func (x *Seat) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Seat) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Seat) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type Reservation struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId            string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TotalPrice         float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Seats              []*Seat                `protobuf:"bytes,5,rep,name=seats,proto3" json:"seats,omitempty"`
	StripeClientSecret string                 `protobuf:"bytes,6,opt,name=stripe_client_secret,json=stripeClientSecret,proto3" json:"stripe_client_secret,omitempty"`
	TimeLeft           *float64               `protobuf:"fixed64,7,opt,name=time_left,json=timeLeft,proto3,oneof" json:"time_left,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_reservation_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *Reservation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Reservation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reservation) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Reservation) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Reservation) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *Reservation) GetStripeClientSecret() string {
	if x != nil {
		return x.StripeClientSecret
	}
	return ""
}

func (x *Reservation) GetTimeLeft() float64 {
	if x != nil && x.TimeLeft != nil {
		return *x.TimeLeft
	}
	return 0
}

func (x *Reservation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,3,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,4,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *CreateReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateReservationRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateReservationRequest) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *CreateReservationRequest) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type DeleteReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationRequest) Reset() {
	*x = DeleteReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationRequest) ProtoMessage() {}

func (x *DeleteReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationRequest.ProtoReflect.Descriptor instead.
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationRequest) Reset() {
	*x = ListReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationRequest) ProtoMessage() {}

func (x *ListReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationRequest.ProtoReflect.Descriptor instead.
func (*ListReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *ListReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *GetReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetReservationByStripeSessionIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationByStripeSessionIDRequest) Reset() {
	*x = GetReservationByStripeSessionIDRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationByStripeSessionIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationByStripeSessionIDRequest) ProtoMessage() {}

func (x *GetReservationByStripeSessionIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationByStripeSessionIDRequest.ProtoReflect.Descriptor instead.
func (*GetReservationByStripeSessionIDRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *GetReservationByStripeSessionIDRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ConfirmReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationRequest) Reset() {
	*x = ConfirmReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationRequest) ProtoMessage() {}

func (x *ConfirmReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationRequest.ProtoReflect.Descriptor instead.
func (*ConfirmReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *ConfirmReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *CreateReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationResponse) Reset() {
	*x = DeleteReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationResponse) ProtoMessage() {}

func (x *DeleteReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationResponse.ProtoReflect.Descriptor instead.
func (*DeleteReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   []*Reservation         `protobuf:"bytes,1,rep,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationResponse) Reset() {
	*x = ListReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationResponse) ProtoMessage() {}

func (x *ListReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationResponse.ProtoReflect.Descriptor instead.
func (*ListReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{11}
}

func (x *ListReservationResponse) GetReservation() []*Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type GetReservationResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId            string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TotalPrice         float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Seats              []*Seat                `protobuf:"bytes,5,rep,name=seats,proto3" json:"seats,omitempty"`
	StripeClientSecret string                 `protobuf:"bytes,6,opt,name=stripe_client_secret,json=stripeClientSecret,proto3" json:"stripe_client_secret,omitempty"`
	TimeLeft           *float64               `protobuf:"fixed64,7,opt,name=time_left,json=timeLeft,proto3,oneof" json:"time_left,omitempty"`
	Status             string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetReservationResponse) Reset() {
	*x = GetReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationResponse) ProtoMessage() {}

func (x *GetReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationResponse.ProtoReflect.Descriptor instead.
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{12}
}

func (x *GetReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetReservationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetReservationResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetReservationResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *GetReservationResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *GetReservationResponse) GetStripeClientSecret() string {
	if x != nil {
		return x.StripeClientSecret
	}
	return ""
}

func (x *GetReservationResponse) GetTimeLeft() float64 {
	if x != nil && x.TimeLeft != nil {
		return *x.TimeLeft
	}
	return 0
}

func (x *GetReservationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ConfirmReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmReservationResponse) Reset() {
	*x = ConfirmReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmReservationResponse) ProtoMessage() {}

func (x *ConfirmReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmReservationResponse.ProtoReflect.Descriptor instead.
func (*ConfirmReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{13}
}

func (x *ConfirmReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmReservationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ConfirmReservationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetReservationByStripeSessionIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,5,rep,name=seats,proto3" json:"seats,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationByStripeSessionIDResponse) Reset() {
	*x = GetReservationByStripeSessionIDResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationByStripeSessionIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationByStripeSessionIDResponse) ProtoMessage() {}

func (x *GetReservationByStripeSessionIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationByStripeSessionIDResponse.ProtoReflect.Descriptor instead.
func (*GetReservationByStripeSessionIDResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{14}
}

func (x *GetReservationByStripeSessionIDResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetReservationByStripeSessionIDResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetReservationByStripeSessionIDResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetReservationByStripeSessionIDResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *GetReservationByStripeSessionIDResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

func (x *GetReservationByStripeSessionIDResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetEventSeatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventSeatsRequest) Reset() {
	*x = GetEventSeatsRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventSeatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventSeatsRequest) ProtoMessage() {}

func (x *GetEventSeatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventSeatsRequest.ProtoReflect.Descriptor instead.
func (*GetEventSeatsRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{15}
}

func (x *GetEventSeatsRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type SeatStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneNumber    int32                  `protobuf:"varint,1,opt,name=zone_number,json=zoneNumber,proto3" json:"zone_number,omitempty"`
	Row           int32                  `protobuf:"varint,2,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,3,opt,name=column,proto3" json:"column,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"` // "AVAILABLE", "PENDING", "RESERVED"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SeatStatus) Reset() {
	*x = SeatStatus{}
	mi := &file_reservation_reservation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatStatus) ProtoMessage() {}

func (x *SeatStatus) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatStatus.ProtoReflect.Descriptor instead.
func (*SeatStatus) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{16}
}

func (x *SeatStatus) GetZoneNumber() int32 {
	if x != nil {
		return x.ZoneNumber
	}
	return 0
}

func (x *SeatStatus) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *SeatStatus) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *SeatStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetEventSeatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seats         []*SeatStatus          `protobuf:"bytes,1,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventSeatsResponse) Reset() {
	*x = GetEventSeatsResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventSeatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventSeatsResponse) ProtoMessage() {}

func (x *GetEventSeatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventSeatsResponse.ProtoReflect.Descriptor instead.
func (*GetEventSeatsResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{17}
}

func (x *GetEventSeatsResponse) GetSeats() []*SeatStatus {
	if x != nil {
		return x.Seats
	}
	return nil
}

var File_reservation_reservation_proto protoreflect.FileDescriptor

const file_reservation_reservation_proto_rawDesc = "" +
	"\n" +
	"\x1dreservation/reservation.proto\x12\vreservation\"\a\n" +
	"\x05Empty\"g\n" +
	"\x04Seat\x12\x1f\n" +
	"\vzone_number\x18\x01 \x01(\x05R\n" +
	"zoneNumber\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x10\n" +
	"\x03row\x18\x04 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x05 \x01(\x05R\x06column\"\x95\x02\n" +
	"\vReservation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12'\n" +
	"\x05seats\x18\x05 \x03(\v2\x11.reservation.SeatR\x05seats\x120\n" +
	"\x14stripe_client_secret\x18\x06 \x01(\tR\x12stripeClientSecret\x12 \n" +
	"\ttime_left\x18\a \x01(\x01H\x00R\btimeLeft\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06statusB\f\n" +
	"\n" +
	"_time_left\"\x98\x01\n" +
	"\x18CreateReservationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1f\n" +
	"\vtotal_price\x18\x03 \x01(\x01R\n" +
	"totalPrice\x12'\n" +
	"\x05seats\x18\x04 \x03(\v2\x11.reservation.SeatR\x05seats\"*\n" +
	"\x18DeleteReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"1\n" +
	"\x16ListReservationRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"'\n" +
	"\x15GetReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"&GetReservationByStripeSessionIDRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"+\n" +
	"\x19ConfirmReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19CreateReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19DeleteReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x17ListReservationResponse\x12:\n" +
	"\vreservation\x18\x01 \x03(\v2\x18.reservation.ReservationR\vreservation\"\xa0\x02\n" +
	"\x16GetReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12'\n" +
	"\x05seats\x18\x05 \x03(\v2\x11.reservation.SeatR\x05seats\x120\n" +
	"\x14stripe_client_secret\x18\x06 \x01(\tR\x12stripeClientSecret\x12 \n" +
	"\ttime_left\x18\a \x01(\x01H\x00R\btimeLeft\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06statusB\f\n" +
	"\n" +
	"_time_left\"`\n" +
	"\x1aConfirmReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\xcf\x01\n" +
	"'GetReservationByStripeSessionIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12'\n" +
	"\x05seats\x18\x05 \x03(\v2\x11.reservation.SeatR\x05seats\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"1\n" +
	"\x14GetEventSeatsRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"o\n" +
	"\n" +
	"SeatStatus\x12\x1f\n" +
	"\vzone_number\x18\x01 \x01(\x05R\n" +
	"zoneNumber\x12\x10\n" +
	"\x03row\x18\x02 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x05R\x06column\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"F\n" +
	"\x15GetEventSeatsResponse\x12-\n" +
	"\x05seats\x18\x01 \x03(\v2\x17.reservation.SeatStatusR\x05seats2\xf1\x05\n" +
	"\x12ReservationService\x12d\n" +
	"\x11CreateReservation\x12%.reservation.CreateReservationRequest\x1a&.reservation.CreateReservationResponse\"\x00\x12d\n" +
	"\x11DeleteReservation\x12%.reservation.DeleteReservationRequest\x1a&.reservation.DeleteReservationResponse\"\x00\x12^\n" +
	"\x0fListReservation\x12#.reservation.ListReservationRequest\x1a$.reservation.ListReservationResponse\"\x00\x12[\n" +
	"\x0eGetReservation\x12\".reservation.GetReservationRequest\x1a#.reservation.GetReservationResponse\"\x00\x12g\n" +
	"\x12ConfirmReservation\x12&.reservation.ConfirmReservationRequest\x1a'.reservation.ConfirmReservationResponse\"\x00\x12\x8e\x01\n" +
	"\x1fGetReservationByStripeSessionID\x123.reservation.GetReservationByStripeSessionIDRequest\x1a4.reservation.GetReservationByStripeSessionIDResponse\"\x00\x12X\n" +
	"\rGetEventSeats\x12!.reservation.GetEventSeatsRequest\x1a\".reservation.GetEventSeatsResponse\"\x00BRZPgithub.com/cp-rektmart/aconcert-microservice/pkg/proto/reservation;reservationpbb\x06proto3"

var (
	file_reservation_reservation_proto_rawDescOnce sync.Once
	file_reservation_reservation_proto_rawDescData []byte
)

func file_reservation_reservation_proto_rawDescGZIP() []byte {
	file_reservation_reservation_proto_rawDescOnce.Do(func() {
		file_reservation_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reservation_reservation_proto_rawDesc), len(file_reservation_reservation_proto_rawDesc)))
	})
	return file_reservation_reservation_proto_rawDescData
}

var file_reservation_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_reservation_reservation_proto_goTypes = []any{
	(*Empty)(nil),                                   // 0: reservation.Empty
	(*Seat)(nil),                                    // 1: reservation.Seat
	(*Reservation)(nil),                             // 2: reservation.Reservation
	(*CreateReservationRequest)(nil),                // 3: reservation.CreateReservationRequest
	(*DeleteReservationRequest)(nil),                // 4: reservation.DeleteReservationRequest
	(*ListReservationRequest)(nil),                  // 5: reservation.ListReservationRequest
	(*GetReservationRequest)(nil),                   // 6: reservation.GetReservationRequest
	(*GetReservationByStripeSessionIDRequest)(nil),  // 7: reservation.GetReservationByStripeSessionIDRequest
	(*ConfirmReservationRequest)(nil),               // 8: reservation.ConfirmReservationRequest
	(*CreateReservationResponse)(nil),               // 9: reservation.CreateReservationResponse
	(*DeleteReservationResponse)(nil),               // 10: reservation.DeleteReservationResponse
	(*ListReservationResponse)(nil),                 // 11: reservation.ListReservationResponse
	(*GetReservationResponse)(nil),                  // 12: reservation.GetReservationResponse
	(*ConfirmReservationResponse)(nil),              // 13: reservation.ConfirmReservationResponse
	(*GetReservationByStripeSessionIDResponse)(nil), // 14: reservation.GetReservationByStripeSessionIDResponse
	(*GetEventSeatsRequest)(nil),                    // 15: reservation.GetEventSeatsRequest
	(*SeatStatus)(nil),                              // 16: reservation.SeatStatus
	(*GetEventSeatsResponse)(nil),                   // 17: reservation.GetEventSeatsResponse
}
var file_reservation_reservation_proto_depIdxs = []int32{
	1,  // 0: reservation.Reservation.seats:type_name -> reservation.Seat
	1,  // 1: reservation.CreateReservationRequest.seats:type_name -> reservation.Seat
	2,  // 2: reservation.ListReservationResponse.reservation:type_name -> reservation.Reservation
	1,  // 3: reservation.GetReservationResponse.seats:type_name -> reservation.Seat
	1,  // 4: reservation.GetReservationByStripeSessionIDResponse.seats:type_name -> reservation.Seat
	16, // 5: reservation.GetEventSeatsResponse.seats:type_name -> reservation.SeatStatus
	3,  // 6: reservation.ReservationService.CreateReservation:input_type -> reservation.CreateReservationRequest
	4,  // 7: reservation.ReservationService.DeleteReservation:input_type -> reservation.DeleteReservationRequest
	5,  // 8: reservation.ReservationService.ListReservation:input_type -> reservation.ListReservationRequest
	6,  // 9: reservation.ReservationService.GetReservation:input_type -> reservation.GetReservationRequest
	8,  // 10: reservation.ReservationService.ConfirmReservation:input_type -> reservation.ConfirmReservationRequest
	7,  // 11: reservation.ReservationService.GetReservationByStripeSessionID:input_type -> reservation.GetReservationByStripeSessionIDRequest
	15, // 12: reservation.ReservationService.GetEventSeats:input_type -> reservation.GetEventSeatsRequest
	9,  // 13: reservation.ReservationService.CreateReservation:output_type -> reservation.CreateReservationResponse
	10, // 14: reservation.ReservationService.DeleteReservation:output_type -> reservation.DeleteReservationResponse
	11, // 15: reservation.ReservationService.ListReservation:output_type -> reservation.ListReservationResponse
	12, // 16: reservation.ReservationService.GetReservation:output_type -> reservation.GetReservationResponse
	13, // 17: reservation.ReservationService.ConfirmReservation:output_type -> reservation.ConfirmReservationResponse
	14, // 18: reservation.ReservationService.GetReservationByStripeSessionID:output_type -> reservation.GetReservationByStripeSessionIDResponse
	17, // 19: reservation.ReservationService.GetEventSeats:output_type -> reservation.GetEventSeatsResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_reservation_reservation_proto_init() }
func file_reservation_reservation_proto_init() {
	if File_reservation_reservation_proto != nil {
		return
	}
	file_reservation_reservation_proto_msgTypes[2].OneofWrappers = []any{}
	file_reservation_reservation_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reservation_reservation_proto_rawDesc), len(file_reservation_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reservation_reservation_proto_goTypes,
		DependencyIndexes: file_reservation_reservation_proto_depIdxs,
		MessageInfos:      file_reservation_reservation_proto_msgTypes,
	}.Build()
	File_reservation_reservation_proto = out.File
	file_reservation_reservation_proto_goTypes = nil
	file_reservation_reservation_proto_depIdxs = nil
}
