// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: reservation/reservation.proto

package reservationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------ Messages ------------------ //
type Seat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneNumber    int32                  `protobuf:"varint,1,opt,name=zone_number,json=zoneNumber,proto3" json:"zone_number,omitempty"`
	ZoneName      string                 `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Exclusive     []string               `protobuf:"bytes,4,rep,name=exclusive,proto3" json:"exclusive,omitempty"`
	Row           int32                  `protobuf:"varint,5,opt,name=row,proto3" json:"row,omitempty"`
	Column        int32                  `protobuf:"varint,6,opt,name=column,proto3" json:"column,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Seat) Reset() {
	*x = Seat{}
	mi := &file_reservation_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Seat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Seat) ProtoMessage() {}

func (x *Seat) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Seat.ProtoReflect.Descriptor instead.
func (*Seat) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *Seat) GetZoneNumber() int32 {
	if x != nil {
		return x.ZoneNumber
	}
	return 0
}

func (x *Seat) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *Seat) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Seat) GetExclusive() []string {
	if x != nil {
		return x.Exclusive
	}
	return nil
}

func (x *Seat) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *Seat) GetColumn() int32 {
	if x != nil {
		return x.Column
	}
	return 0
}

type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=eventId,proto3" json:"eventId,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_reservation_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *Reservation) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Reservation) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Reservation) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Reservation) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

type CreateReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   *Reservation           `protobuf:"bytes,1,opt,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationRequest) Reset() {
	*x = CreateReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationRequest) ProtoMessage() {}

func (x *CreateReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationRequest.ProtoReflect.Descriptor instead.
func (*CreateReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *CreateReservationRequest) GetReservation() *Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type DeleteReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationRequest) Reset() {
	*x = DeleteReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationRequest) ProtoMessage() {}

func (x *DeleteReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationRequest.ProtoReflect.Descriptor instead.
func (*DeleteReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationRequest) Reset() {
	*x = ListReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationRequest) ProtoMessage() {}

func (x *ListReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationRequest.ProtoReflect.Descriptor instead.
func (*ListReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *ListReservationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationRequest) Reset() {
	*x = GetReservationRequest{}
	mi := &file_reservation_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationRequest) ProtoMessage() {}

func (x *GetReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationRequest.ProtoReflect.Descriptor instead.
func (*GetReservationRequest) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *GetReservationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CreateReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateReservationResponse) Reset() {
	*x = CreateReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReservationResponse) ProtoMessage() {}

func (x *CreateReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReservationResponse.ProtoReflect.Descriptor instead.
func (*CreateReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *CreateReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteReservationResponse) Reset() {
	*x = DeleteReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteReservationResponse) ProtoMessage() {}

func (x *DeleteReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteReservationResponse.ProtoReflect.Descriptor instead.
func (*DeleteReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservation   []*Reservation         `protobuf:"bytes,1,rep,name=reservation,proto3" json:"reservation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReservationResponse) Reset() {
	*x = ListReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReservationResponse) ProtoMessage() {}

func (x *ListReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReservationResponse.ProtoReflect.Descriptor instead.
func (*ListReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *ListReservationResponse) GetReservation() []*Reservation {
	if x != nil {
		return x.Reservation
	}
	return nil
}

type GetReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=eventId,proto3" json:"eventId,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,4,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	Seats         []*Seat                `protobuf:"bytes,5,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReservationResponse) Reset() {
	*x = GetReservationResponse{}
	mi := &file_reservation_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReservationResponse) ProtoMessage() {}

func (x *GetReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_reservation_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReservationResponse.ProtoReflect.Descriptor instead.
func (*GetReservationResponse) Descriptor() ([]byte, []int) {
	return file_reservation_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *GetReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetReservationResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetReservationResponse) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *GetReservationResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *GetReservationResponse) GetSeats() []*Seat {
	if x != nil {
		return x.Seats
	}
	return nil
}

var File_reservation_reservation_proto protoreflect.FileDescriptor

const file_reservation_reservation_proto_rawDesc = "" +
	"\n" +
	"\x1dreservation/reservation.proto\x12\vreservation\"\xa2\x01\n" +
	"\x04Seat\x12\x1f\n" +
	"\vzone_number\x18\x01 \x01(\x05R\n" +
	"zoneNumber\x12\x1b\n" +
	"\tzone_name\x18\x02 \x01(\tR\bzoneName\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1c\n" +
	"\texclusive\x18\x04 \x03(\tR\texclusive\x12\x10\n" +
	"\x03row\x18\x05 \x01(\x05R\x03row\x12\x16\n" +
	"\x06column\x18\x06 \x01(\x05R\x06column\"\x88\x01\n" +
	"\vReservation\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\aeventId\x18\x02 \x01(\tR\aeventId\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12'\n" +
	"\x05seats\x18\x03 \x03(\v2\x11.reservation.SeatR\x05seats\"V\n" +
	"\x18CreateReservationRequest\x12:\n" +
	"\vreservation\x18\x01 \x01(\v2\x18.reservation.ReservationR\vreservation\"*\n" +
	"\x18DeleteReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x16ListReservationRequest\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\"'\n" +
	"\x15GetReservationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19CreateReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x19DeleteReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x17ListReservationResponse\x12:\n" +
	"\vreservation\x18\x01 \x03(\v2\x18.reservation.ReservationR\vreservation\"\xa3\x01\n" +
	"\x16GetReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\aeventId\x18\x03 \x01(\tR\aeventId\x12\x1e\n" +
	"\n" +
	"totalPrice\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12'\n" +
	"\x05seats\x18\x05 \x03(\v2\x11.reservation.SeatR\x05seats2\x90\x03\n" +
	"\x12ReservationService\x12W\n" +
	"\x11CreateReservation\x12\x18.reservation.Reservation\x1a&.reservation.CreateReservationResponse\"\x00\x12d\n" +
	"\x11DeleteReservation\x12%.reservation.DeleteReservationRequest\x1a&.reservation.DeleteReservationResponse\"\x00\x12^\n" +
	"\x0fListReservation\x12#.reservation.ListReservationRequest\x1a$.reservation.ListReservationResponse\"\x00\x12[\n" +
	"\x0eGetReservation\x12\".reservation.GetReservationRequest\x1a#.reservation.GetReservationResponse\"\x00BRZPgithub.com/cp-rektmart/aconcert-microservice/pkg/proto/reservation;reservationpbb\x06proto3"

var (
	file_reservation_reservation_proto_rawDescOnce sync.Once
	file_reservation_reservation_proto_rawDescData []byte
)

func file_reservation_reservation_proto_rawDescGZIP() []byte {
	file_reservation_reservation_proto_rawDescOnce.Do(func() {
		file_reservation_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reservation_reservation_proto_rawDesc), len(file_reservation_reservation_proto_rawDesc)))
	})
	return file_reservation_reservation_proto_rawDescData
}

var file_reservation_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_reservation_reservation_proto_goTypes = []any{
	(*Seat)(nil),                      // 0: reservation.Seat
	(*Reservation)(nil),               // 1: reservation.Reservation
	(*CreateReservationRequest)(nil),  // 2: reservation.CreateReservationRequest
	(*DeleteReservationRequest)(nil),  // 3: reservation.DeleteReservationRequest
	(*ListReservationRequest)(nil),    // 4: reservation.ListReservationRequest
	(*GetReservationRequest)(nil),     // 5: reservation.GetReservationRequest
	(*CreateReservationResponse)(nil), // 6: reservation.CreateReservationResponse
	(*DeleteReservationResponse)(nil), // 7: reservation.DeleteReservationResponse
	(*ListReservationResponse)(nil),   // 8: reservation.ListReservationResponse
	(*GetReservationResponse)(nil),    // 9: reservation.GetReservationResponse
}
var file_reservation_reservation_proto_depIdxs = []int32{
	0, // 0: reservation.Reservation.seats:type_name -> reservation.Seat
	1, // 1: reservation.CreateReservationRequest.reservation:type_name -> reservation.Reservation
	1, // 2: reservation.ListReservationResponse.reservation:type_name -> reservation.Reservation
	0, // 3: reservation.GetReservationResponse.seats:type_name -> reservation.Seat
	1, // 4: reservation.ReservationService.CreateReservation:input_type -> reservation.Reservation
	3, // 5: reservation.ReservationService.DeleteReservation:input_type -> reservation.DeleteReservationRequest
	4, // 6: reservation.ReservationService.ListReservation:input_type -> reservation.ListReservationRequest
	5, // 7: reservation.ReservationService.GetReservation:input_type -> reservation.GetReservationRequest
	6, // 8: reservation.ReservationService.CreateReservation:output_type -> reservation.CreateReservationResponse
	7, // 9: reservation.ReservationService.DeleteReservation:output_type -> reservation.DeleteReservationResponse
	8, // 10: reservation.ReservationService.ListReservation:output_type -> reservation.ListReservationResponse
	9, // 11: reservation.ReservationService.GetReservation:output_type -> reservation.GetReservationResponse
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_reservation_reservation_proto_init() }
func file_reservation_reservation_proto_init() {
	if File_reservation_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reservation_reservation_proto_rawDesc), len(file_reservation_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_reservation_reservation_proto_goTypes,
		DependencyIndexes: file_reservation_reservation_proto_depIdxs,
		MessageInfos:      file_reservation_reservation_proto_msgTypes,
	}.Build()
	File_reservation_reservation_proto = out.File
	file_reservation_reservation_proto_goTypes = nil
	file_reservation_reservation_proto_depIdxs = nil
}
