// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	LocationID  pgtype.UUID        `json:"location_id"`
	Artist      []string           `json:"artist"`
	EventDate   pgtype.Timestamptz `json:"event_date"`
	Thumbnail   pgtype.Text        `json:"thumbnail"`
	Images      []string           `json:"images"`
}
