// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Insert a new event
	CreateEvent(ctx context.Context, arg CreateEventParams) (pgtype.UUID, error)
	// Soft delete an event
	DeleteEvent(ctx context.Context, id pgtype.UUID) (interface{}, error)
	// Get a single event by ID
	GetEventByID(ctx context.Context, id pgtype.UUID) (Event, error)
	// Hard delete an event (for admin use)
	HardDeleteEvent(ctx context.Context, id pgtype.UUID) (interface{}, error)
	// List all events
	ListEvents(ctx context.Context) ([]Event, error)
	// Update an existing event
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
