// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: location/location.proto

package locationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ------------------ Messages ------------------ //
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VenueName     string                 `protobuf:"bytes,2,opt,name=venue_name,json=venueName,proto3" json:"venue_name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	StateProvince string                 `protobuf:"bytes,4,opt,name=state_province,json=stateProvince,proto3" json:"state_province,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Zones         []*Zone                `protobuf:"bytes,8,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_location_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Location) GetVenueName() string {
	if x != nil {
		return x.VenueName
	}
	return ""
}

func (x *Location) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Location) GetStateProvince() string {
	if x != nil {
		return x.StateProvince
	}
	return ""
}

func (x *Location) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Location) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Location) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

type Zone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ZoneNumber    int32                  `protobuf:"varint,1,opt,name=zone_number,json=zoneNumber,proto3" json:"zone_number,omitempty"`
	ZoneName      string                 `protobuf:"bytes,2,opt,name=zone_name,json=zoneName,proto3" json:"zone_name,omitempty"`
	Capacity      int32                  `protobuf:"varint,3,opt,name=capacity,proto3" json:"capacity,omitempty"`
	SeatsPerRow   int32                  `protobuf:"varint,4,opt,name=seatsPerRow,proto3" json:"seatsPerRow,omitempty"`
	NumberOfRows  int32                  `protobuf:"varint,5,opt,name=numberOfRows,proto3" json:"numberOfRows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Zone) Reset() {
	*x = Zone{}
	mi := &file_location_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Zone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zone) ProtoMessage() {}

func (x *Zone) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zone.ProtoReflect.Descriptor instead.
func (*Zone) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{1}
}

func (x *Zone) GetZoneNumber() int32 {
	if x != nil {
		return x.ZoneNumber
	}
	return 0
}

func (x *Zone) GetZoneName() string {
	if x != nil {
		return x.ZoneName
	}
	return ""
}

func (x *Zone) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Zone) GetSeatsPerRow() int32 {
	if x != nil {
		return x.SeatsPerRow
	}
	return 0
}

func (x *Zone) GetNumberOfRows() int32 {
	if x != nil {
		return x.NumberOfRows
	}
	return 0
}

type LocationIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationIdResponse) Reset() {
	*x = LocationIdResponse{}
	mi := &file_location_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationIdResponse) ProtoMessage() {}

func (x *LocationIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationIdResponse.ProtoReflect.Descriptor instead.
func (*LocationIdResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{2}
}

func (x *LocationIdResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// ------------------ CRUD Requests ------------------ //
type GetLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationRequest) Reset() {
	*x = GetLocationRequest{}
	mi := &file_location_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationRequest) ProtoMessage() {}

func (x *GetLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationRequest.ProtoReflect.Descriptor instead.
func (*GetLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{3}
}

func (x *GetLocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsRequest) Reset() {
	*x = ListLocationsRequest{}
	mi := &file_location_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsRequest) ProtoMessage() {}

func (x *ListLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsRequest.ProtoReflect.Descriptor instead.
func (*ListLocationsRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{4}
}

type ListLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLocationsResponse) Reset() {
	*x = ListLocationsResponse{}
	mi := &file_location_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLocationsResponse) ProtoMessage() {}

func (x *ListLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLocationsResponse.ProtoReflect.Descriptor instead.
func (*ListLocationsResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{5}
}

func (x *ListLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	VenueName     string                 `protobuf:"bytes,2,opt,name=venue_name,json=venueName,proto3" json:"venue_name,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	StateProvince string                 `protobuf:"bytes,4,opt,name=state_province,json=stateProvince,proto3" json:"state_province,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Latitude      float64                `protobuf:"fixed64,6,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,7,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Zones         []*Zone                `protobuf:"bytes,8,rep,name=zones,proto3" json:"zones,omitempty"` // optional, can update zones together
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_location_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateLocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLocationRequest) GetVenueName() string {
	if x != nil {
		return x.VenueName
	}
	return ""
}

func (x *UpdateLocationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UpdateLocationRequest) GetStateProvince() string {
	if x != nil {
		return x.StateProvince
	}
	return ""
}

func (x *UpdateLocationRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *UpdateLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *UpdateLocationRequest) GetZones() []*Zone {
	if x != nil {
		return x.Zones
	}
	return nil
}

type DeleteLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocationRequest) Reset() {
	*x = DeleteLocationRequest{}
	mi := &file_location_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocationRequest) ProtoMessage() {}

func (x *DeleteLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLocationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocationResponse) Reset() {
	*x = DeleteLocationResponse{}
	mi := &file_location_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocationResponse) ProtoMessage() {}

func (x *DeleteLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocationResponse.ProtoReflect.Descriptor instead.
func (*DeleteLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ------------------ Zone Requests ------------------ //
type AddZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Zone          *Zone                  `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddZoneRequest) Reset() {
	*x = AddZoneRequest{}
	mi := &file_location_location_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddZoneRequest) ProtoMessage() {}

func (x *AddZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddZoneRequest.ProtoReflect.Descriptor instead.
func (*AddZoneRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{9}
}

func (x *AddZoneRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *AddZoneRequest) GetZone() *Zone {
	if x != nil {
		return x.Zone
	}
	return nil
}

type RemoveZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    string                 `protobuf:"bytes,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	ZoneNumber    int32                  `protobuf:"varint,2,opt,name=zone_number,json=zoneNumber,proto3" json:"zone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveZoneRequest) Reset() {
	*x = RemoveZoneRequest{}
	mi := &file_location_location_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveZoneRequest) ProtoMessage() {}

func (x *RemoveZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_location_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveZoneRequest.ProtoReflect.Descriptor instead.
func (*RemoveZoneRequest) Descriptor() ([]byte, []int) {
	return file_location_location_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveZoneRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *RemoveZoneRequest) GetZoneNumber() int32 {
	if x != nil {
		return x.ZoneNumber
	}
	return 0
}

var File_location_location_proto protoreflect.FileDescriptor

const file_location_location_proto_rawDesc = "" +
	"\n" +
	"\x17location/location.proto\x12\blocation\"\xee\x01\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"venue_name\x18\x02 \x01(\tR\tvenueName\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12%\n" +
	"\x0estate_province\x18\x04 \x01(\tR\rstateProvince\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12$\n" +
	"\x05zones\x18\b \x03(\v2\x0e.location.ZoneR\x05zones\"\xa6\x01\n" +
	"\x04Zone\x12\x1f\n" +
	"\vzone_number\x18\x01 \x01(\x05R\n" +
	"zoneNumber\x12\x1b\n" +
	"\tzone_name\x18\x02 \x01(\tR\bzoneName\x12\x1a\n" +
	"\bcapacity\x18\x03 \x01(\x05R\bcapacity\x12 \n" +
	"\vseatsPerRow\x18\x04 \x01(\x05R\vseatsPerRow\x12\"\n" +
	"\fnumberOfRows\x18\x05 \x01(\x05R\fnumberOfRows\"$\n" +
	"\x12LocationIdResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12GetLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x16\n" +
	"\x14ListLocationsRequest\"I\n" +
	"\x15ListLocationsResponse\x120\n" +
	"\tlocations\x18\x01 \x03(\v2\x12.location.LocationR\tlocations\"\xfb\x01\n" +
	"\x15UpdateLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"venue_name\x18\x02 \x01(\tR\tvenueName\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12%\n" +
	"\x0estate_province\x18\x04 \x01(\tR\rstateProvince\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1a\n" +
	"\blatitude\x18\x06 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\a \x01(\x01R\tlongitude\x12$\n" +
	"\x05zones\x18\b \x03(\v2\x0e.location.ZoneR\x05zones\"'\n" +
	"\x15DeleteLocationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"U\n" +
	"\x0eAddZoneRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12\"\n" +
	"\x04zone\x18\x02 \x01(\v2\x0e.location.ZoneR\x04zone\"U\n" +
	"\x11RemoveZoneRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\tR\n" +
	"locationId\x12\x1f\n" +
	"\vzone_number\x18\x02 \x01(\x05R\n" +
	"zoneNumber2\x9a\x04\n" +
	"\x0fLocationService\x12B\n" +
	"\x0eCreateLocation\x12\x12.location.Location\x1a\x1c.location.LocationIdResponse\x12?\n" +
	"\vGetLocation\x12\x1c.location.GetLocationRequest\x1a\x12.location.Location\x12P\n" +
	"\rListLocations\x12\x1e.location.ListLocationsRequest\x1a\x1f.location.ListLocationsResponse\x12O\n" +
	"\x0eUpdateLocation\x12\x1f.location.UpdateLocationRequest\x1a\x1c.location.LocationIdResponse\x12S\n" +
	"\x0eDeleteLocation\x12\x1f.location.DeleteLocationRequest\x1a .location.DeleteLocationResponse\x12A\n" +
	"\aAddZone\x12\x18.location.AddZoneRequest\x1a\x1c.location.LocationIdResponse\x12G\n" +
	"\n" +
	"RemoveZone\x12\x1b.location.RemoveZoneRequest\x1a\x1c.location.LocationIdResponseBLZJgithub.com/cp-rektmart/aconcert-microservice/pkg/proto/location;locationpbb\x06proto3"

var (
	file_location_location_proto_rawDescOnce sync.Once
	file_location_location_proto_rawDescData []byte
)

func file_location_location_proto_rawDescGZIP() []byte {
	file_location_location_proto_rawDescOnce.Do(func() {
		file_location_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)))
	})
	return file_location_location_proto_rawDescData
}

var file_location_location_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_location_location_proto_goTypes = []any{
	(*Location)(nil),               // 0: location.Location
	(*Zone)(nil),                   // 1: location.Zone
	(*LocationIdResponse)(nil),     // 2: location.LocationIdResponse
	(*GetLocationRequest)(nil),     // 3: location.GetLocationRequest
	(*ListLocationsRequest)(nil),   // 4: location.ListLocationsRequest
	(*ListLocationsResponse)(nil),  // 5: location.ListLocationsResponse
	(*UpdateLocationRequest)(nil),  // 6: location.UpdateLocationRequest
	(*DeleteLocationRequest)(nil),  // 7: location.DeleteLocationRequest
	(*DeleteLocationResponse)(nil), // 8: location.DeleteLocationResponse
	(*AddZoneRequest)(nil),         // 9: location.AddZoneRequest
	(*RemoveZoneRequest)(nil),      // 10: location.RemoveZoneRequest
}
var file_location_location_proto_depIdxs = []int32{
	1,  // 0: location.Location.zones:type_name -> location.Zone
	0,  // 1: location.ListLocationsResponse.locations:type_name -> location.Location
	1,  // 2: location.UpdateLocationRequest.zones:type_name -> location.Zone
	1,  // 3: location.AddZoneRequest.zone:type_name -> location.Zone
	0,  // 4: location.LocationService.CreateLocation:input_type -> location.Location
	3,  // 5: location.LocationService.GetLocation:input_type -> location.GetLocationRequest
	4,  // 6: location.LocationService.ListLocations:input_type -> location.ListLocationsRequest
	6,  // 7: location.LocationService.UpdateLocation:input_type -> location.UpdateLocationRequest
	7,  // 8: location.LocationService.DeleteLocation:input_type -> location.DeleteLocationRequest
	9,  // 9: location.LocationService.AddZone:input_type -> location.AddZoneRequest
	10, // 10: location.LocationService.RemoveZone:input_type -> location.RemoveZoneRequest
	2,  // 11: location.LocationService.CreateLocation:output_type -> location.LocationIdResponse
	0,  // 12: location.LocationService.GetLocation:output_type -> location.Location
	5,  // 13: location.LocationService.ListLocations:output_type -> location.ListLocationsResponse
	2,  // 14: location.LocationService.UpdateLocation:output_type -> location.LocationIdResponse
	8,  // 15: location.LocationService.DeleteLocation:output_type -> location.DeleteLocationResponse
	2,  // 16: location.LocationService.AddZone:output_type -> location.LocationIdResponse
	2,  // 17: location.LocationService.RemoveZone:output_type -> location.LocationIdResponse
	11, // [11:18] is the sub-list for method output_type
	4,  // [4:11] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_location_location_proto_init() }
func file_location_location_proto_init() {
	if File_location_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_location_proto_rawDesc), len(file_location_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_location_location_proto_goTypes,
		DependencyIndexes: file_location_location_proto_depIdxs,
		MessageInfos:      file_location_location_proto_msgTypes,
	}.Build()
	File_location_location_proto = out.File
	file_location_location_proto_goTypes = nil
	file_location_location_proto_depIdxs = nil
}
