// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: event/event.proto

package eventpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event message
type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LocationId    string                 `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Artist        []string               `protobuf:"bytes,5,rep,name=artist,proto3" json:"artist,omitempty"`
	EventDate     string                 `protobuf:"bytes,6,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,7,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Images        []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     string                 `protobuf:"bytes,11,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_event_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Event) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Event) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *Event) GetArtist() []string {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *Event) GetEventDate() string {
	if x != nil {
		return x.EventDate
	}
	return ""
}

func (x *Event) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *Event) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Event) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Event) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Event) GetDeletedAt() string {
	if x != nil {
		return x.DeletedAt
	}
	return ""
}

// CreateEvent
type CreateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	Artist        []string               `protobuf:"bytes,4,rep,name=artist,proto3" json:"artist,omitempty"`
	EventDate     string                 `protobuf:"bytes,5,opt,name=event_date,json=eventDate,proto3" json:"event_date,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,6,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Images        []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventRequest) Reset() {
	*x = CreateEventRequest{}
	mi := &file_event_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventRequest) ProtoMessage() {}

func (x *CreateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventRequest.ProtoReflect.Descriptor instead.
func (*CreateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{1}
}

func (x *CreateEventRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateEventRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreateEventRequest) GetArtist() []string {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *CreateEventRequest) GetEventDate() string {
	if x != nil {
		return x.EventDate
	}
	return ""
}

func (x *CreateEventRequest) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *CreateEventRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type CreateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventResponse) Reset() {
	*x = CreateEventResponse{}
	mi := &file_event_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventResponse) ProtoMessage() {}

func (x *CreateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventResponse.ProtoReflect.Descriptor instead.
func (*CreateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{2}
}

func (x *CreateEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// GetEvent
type GetEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventRequest) Reset() {
	*x = GetEventRequest{}
	mi := &file_event_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventRequest) ProtoMessage() {}

func (x *GetEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventRequest.ProtoReflect.Descriptor instead.
func (*GetEventRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{3}
}

func (x *GetEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Event         *Event                 `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventResponse) Reset() {
	*x = GetEventResponse{}
	mi := &file_event_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventResponse) ProtoMessage() {}

func (x *GetEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventResponse.ProtoReflect.Descriptor instead.
func (*GetEventResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{4}
}

func (x *GetEventResponse) GetEvent() *Event {
	if x != nil {
		return x.Event
	}
	return nil
}

// UpdateEvent
type UpdateEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	LocationId    *string                `protobuf:"bytes,4,opt,name=location_id,json=locationId,proto3,oneof" json:"location_id,omitempty"`
	Artist        []string               `protobuf:"bytes,5,rep,name=artist,proto3" json:"artist,omitempty"`
	EventDate     *string                `protobuf:"bytes,6,opt,name=event_date,json=eventDate,proto3,oneof" json:"event_date,omitempty"`
	Thumbnail     *string                `protobuf:"bytes,7,opt,name=thumbnail,proto3,oneof" json:"thumbnail,omitempty"`
	Images        []string               `protobuf:"bytes,8,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventRequest) Reset() {
	*x = UpdateEventRequest{}
	mi := &file_event_event_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventRequest) ProtoMessage() {}

func (x *UpdateEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateEventRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateEventRequest) GetLocationId() string {
	if x != nil && x.LocationId != nil {
		return *x.LocationId
	}
	return ""
}

func (x *UpdateEventRequest) GetArtist() []string {
	if x != nil {
		return x.Artist
	}
	return nil
}

func (x *UpdateEventRequest) GetEventDate() string {
	if x != nil && x.EventDate != nil {
		return *x.EventDate
	}
	return ""
}

func (x *UpdateEventRequest) GetThumbnail() string {
	if x != nil && x.Thumbnail != nil {
		return *x.Thumbnail
	}
	return ""
}

func (x *UpdateEventRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type UpdateEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventResponse) Reset() {
	*x = UpdateEventResponse{}
	mi := &file_event_event_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventResponse) ProtoMessage() {}

func (x *UpdateEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// DeleteEvent
type DeleteEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventRequest) Reset() {
	*x = DeleteEventRequest{}
	mi := &file_event_event_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventRequest) ProtoMessage() {}

func (x *DeleteEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteEventRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty response - no fields needed
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventResponse) Reset() {
	*x = DeleteEventResponse{}
	mi := &file_event_event_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventResponse) ProtoMessage() {}

func (x *DeleteEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventResponse.ProtoReflect.Descriptor instead.
func (*DeleteEventResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteEventResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	TotalPages    int32                  `protobuf:"varint,5,opt,name=total_pages,json=totalPages,proto3" json:"total_pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	mi := &file_event_event_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{9}
}

func (x *Pagination) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Pagination) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Pagination) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *Pagination) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetTotalPages() int32 {
	if x != nil {
		return x.TotalPages
	}
	return 0
}

// ListEvents request with sorting, ordering, and pagination
type ListEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         *string                `protobuf:"bytes,1,opt,name=query,proto3,oneof" json:"query,omitempty"`                 // search keyword
	SortBy        *string                `protobuf:"bytes,2,opt,name=sort_by,json=sortBy,proto3,oneof" json:"sort_by,omitempty"` // field to sort by (e.g., "name", "event_date")
	Order         *string                `protobuf:"bytes,3,opt,name=order,proto3,oneof" json:"order,omitempty"`                 // "asc" or "desc"
	Limit         *int32                 `protobuf:"varint,4,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                // number of items per page
	Page          *int32                 `protobuf:"varint,5,opt,name=page,proto3,oneof" json:"page,omitempty"`                  // page number
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsRequest) Reset() {
	*x = ListEventsRequest{}
	mi := &file_event_event_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsRequest) ProtoMessage() {}

func (x *ListEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsRequest.ProtoReflect.Descriptor instead.
func (*ListEventsRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{10}
}

func (x *ListEventsRequest) GetQuery() string {
	if x != nil && x.Query != nil {
		return *x.Query
	}
	return ""
}

func (x *ListEventsRequest) GetSortBy() string {
	if x != nil && x.SortBy != nil {
		return *x.SortBy
	}
	return ""
}

func (x *ListEventsRequest) GetOrder() string {
	if x != nil && x.Order != nil {
		return *x.Order
	}
	return ""
}

func (x *ListEventsRequest) GetLimit() int32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *ListEventsRequest) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

type ListEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Pagination    *Pagination            `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEventsResponse) Reset() {
	*x = ListEventsResponse{}
	mi := &file_event_event_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEventsResponse) ProtoMessage() {}

func (x *ListEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEventsResponse.ProtoReflect.Descriptor instead.
func (*ListEventsResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{11}
}

func (x *ListEventsResponse) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListEventsResponse) GetPagination() *Pagination {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_event_event_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{12}
}

// EventZone message
type EventZone struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       string                 `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	ZoneNumber    int32                  `protobuf:"varint,4,opt,name=zone_number,json=zoneNumber,proto3" json:"zone_number,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Color         string                 `protobuf:"bytes,6,opt,name=color,proto3" json:"color,omitempty"`
	Name          string                 `protobuf:"bytes,7,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	IsSoldOut     bool                   `protobuf:"varint,9,opt,name=is_sold_out,json=isSoldOut,proto3" json:"is_sold_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventZone) Reset() {
	*x = EventZone{}
	mi := &file_event_event_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventZone) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventZone) ProtoMessage() {}

func (x *EventZone) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventZone.ProtoReflect.Descriptor instead.
func (*EventZone) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{13}
}

func (x *EventZone) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EventZone) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventZone) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *EventZone) GetZoneNumber() int32 {
	if x != nil {
		return x.ZoneNumber
	}
	return 0
}

func (x *EventZone) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *EventZone) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *EventZone) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EventZone) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *EventZone) GetIsSoldOut() bool {
	if x != nil {
		return x.IsSoldOut
	}
	return false
}

type CreateEventZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	LocationId    string                 `protobuf:"bytes,2,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	ZoneNumber    int32                  `protobuf:"varint,3,opt,name=zone_number,json=zoneNumber,proto3" json:"zone_number,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Color         string                 `protobuf:"bytes,5,opt,name=color,proto3" json:"color,omitempty"`
	Name          string                 `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventZoneRequest) Reset() {
	*x = CreateEventZoneRequest{}
	mi := &file_event_event_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventZoneRequest) ProtoMessage() {}

func (x *CreateEventZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventZoneRequest.ProtoReflect.Descriptor instead.
func (*CreateEventZoneRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{14}
}

func (x *CreateEventZoneRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *CreateEventZoneRequest) GetLocationId() string {
	if x != nil {
		return x.LocationId
	}
	return ""
}

func (x *CreateEventZoneRequest) GetZoneNumber() int32 {
	if x != nil {
		return x.ZoneNumber
	}
	return 0
}

func (x *CreateEventZoneRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateEventZoneRequest) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CreateEventZoneRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateEventZoneRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateEventZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEventZoneResponse) Reset() {
	*x = CreateEventZoneResponse{}
	mi := &file_event_event_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEventZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEventZoneResponse) ProtoMessage() {}

func (x *CreateEventZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEventZoneResponse.ProtoReflect.Descriptor instead.
func (*CreateEventZoneResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{15}
}

func (x *CreateEventZoneResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetEventZoneByEventIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       string                 `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventZoneByEventIdRequest) Reset() {
	*x = GetEventZoneByEventIdRequest{}
	mi := &file_event_event_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventZoneByEventIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventZoneByEventIdRequest) ProtoMessage() {}

func (x *GetEventZoneByEventIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventZoneByEventIdRequest.ProtoReflect.Descriptor instead.
func (*GetEventZoneByEventIdRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{16}
}

func (x *GetEventZoneByEventIdRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

type GetEventZoneByEventIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*EventZone           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEventZoneByEventIdResponse) Reset() {
	*x = GetEventZoneByEventIdResponse{}
	mi := &file_event_event_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEventZoneByEventIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEventZoneByEventIdResponse) ProtoMessage() {}

func (x *GetEventZoneByEventIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEventZoneByEventIdResponse.ProtoReflect.Descriptor instead.
func (*GetEventZoneByEventIdResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{17}
}

func (x *GetEventZoneByEventIdResponse) GetList() []*EventZone {
	if x != nil {
		return x.List
	}
	return nil
}

type UpdateEventZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventId       *string                `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3,oneof" json:"event_id,omitempty"`
	LocationId    *string                `protobuf:"bytes,3,opt,name=location_id,json=locationId,proto3,oneof" json:"location_id,omitempty"`
	ZoneNumber    *int32                 `protobuf:"varint,4,opt,name=zone_number,json=zoneNumber,proto3,oneof" json:"zone_number,omitempty"`
	Price         *float64               `protobuf:"fixed64,5,opt,name=price,proto3,oneof" json:"price,omitempty"`
	Color         *string                `protobuf:"bytes,6,opt,name=color,proto3,oneof" json:"color,omitempty"`
	Name          *string                `protobuf:"bytes,7,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,8,opt,name=description,proto3,oneof" json:"description,omitempty"`
	IsSoldOut     *bool                  `protobuf:"varint,9,opt,name=is_sold_out,json=isSoldOut,proto3,oneof" json:"is_sold_out,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventZoneRequest) Reset() {
	*x = UpdateEventZoneRequest{}
	mi := &file_event_event_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventZoneRequest) ProtoMessage() {}

func (x *UpdateEventZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventZoneRequest.ProtoReflect.Descriptor instead.
func (*UpdateEventZoneRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateEventZoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateEventZoneRequest) GetEventId() string {
	if x != nil && x.EventId != nil {
		return *x.EventId
	}
	return ""
}

func (x *UpdateEventZoneRequest) GetLocationId() string {
	if x != nil && x.LocationId != nil {
		return *x.LocationId
	}
	return ""
}

func (x *UpdateEventZoneRequest) GetZoneNumber() int32 {
	if x != nil && x.ZoneNumber != nil {
		return *x.ZoneNumber
	}
	return 0
}

func (x *UpdateEventZoneRequest) GetPrice() float64 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

func (x *UpdateEventZoneRequest) GetColor() string {
	if x != nil && x.Color != nil {
		return *x.Color
	}
	return ""
}

func (x *UpdateEventZoneRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateEventZoneRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateEventZoneRequest) GetIsSoldOut() bool {
	if x != nil && x.IsSoldOut != nil {
		return *x.IsSoldOut
	}
	return false
}

type UpdateEventZoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEventZoneResponse) Reset() {
	*x = UpdateEventZoneResponse{}
	mi := &file_event_event_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEventZoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEventZoneResponse) ProtoMessage() {}

func (x *UpdateEventZoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEventZoneResponse.ProtoReflect.Descriptor instead.
func (*UpdateEventZoneResponse) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateEventZoneResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteEventZoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEventZoneRequest) Reset() {
	*x = DeleteEventZoneRequest{}
	mi := &file_event_event_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEventZoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEventZoneRequest) ProtoMessage() {}

func (x *DeleteEventZoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_event_event_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEventZoneRequest.ProtoReflect.Descriptor instead.
func (*DeleteEventZoneRequest) Descriptor() ([]byte, []int) {
	return file_event_event_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteEventZoneRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_event_event_proto protoreflect.FileDescriptor

const file_event_event_proto_rawDesc = "" +
	"\n" +
	"\x11event/event.proto\x12\x05event\"\xb8\x02\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\tR\n" +
	"locationId\x12\x16\n" +
	"\x06artist\x18\x05 \x03(\tR\x06artist\x12\x1d\n" +
	"\n" +
	"event_date\x18\x06 \x01(\tR\teventDate\x12\x1c\n" +
	"\tthumbnail\x18\a \x01(\tR\tthumbnail\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06images\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"deleted_at\x18\v \x01(\tR\tdeletedAt\"\xd8\x01\n" +
	"\x12CreateEventRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x16\n" +
	"\x06artist\x18\x04 \x03(\tR\x06artist\x12\x1d\n" +
	"\n" +
	"event_date\x18\x05 \x01(\tR\teventDate\x12\x1c\n" +
	"\tthumbnail\x18\x06 \x01(\tR\tthumbnail\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\"%\n" +
	"\x13CreateEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fGetEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"6\n" +
	"\x10GetEventResponse\x12\"\n" +
	"\x05event\x18\x01 \x01(\v2\f.event.EventR\x05event\"\xc7\x02\n" +
	"\x12UpdateEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12$\n" +
	"\vlocation_id\x18\x04 \x01(\tH\x02R\n" +
	"locationId\x88\x01\x01\x12\x16\n" +
	"\x06artist\x18\x05 \x03(\tR\x06artist\x12\"\n" +
	"\n" +
	"event_date\x18\x06 \x01(\tH\x03R\teventDate\x88\x01\x01\x12!\n" +
	"\tthumbnail\x18\a \x01(\tH\x04R\tthumbnail\x88\x01\x01\x12\x16\n" +
	"\x06images\x18\b \x03(\tR\x06imagesB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_location_idB\r\n" +
	"\v_event_dateB\f\n" +
	"\n" +
	"_thumbnail\"%\n" +
	"\x13UpdateEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"$\n" +
	"\x12DeleteEventRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13DeleteEventResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x83\x01\n" +
	"\n" +
	"Pagination\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x1f\n" +
	"\vtotal_pages\x18\x05 \x01(\x05R\n" +
	"totalPages\"\xce\x01\n" +
	"\x11ListEventsRequest\x12\x19\n" +
	"\x05query\x18\x01 \x01(\tH\x00R\x05query\x88\x01\x01\x12\x1c\n" +
	"\asort_by\x18\x02 \x01(\tH\x01R\x06sortBy\x88\x01\x01\x12\x19\n" +
	"\x05order\x18\x03 \x01(\tH\x02R\x05order\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x04 \x01(\x05H\x03R\x05limit\x88\x01\x01\x12\x17\n" +
	"\x04page\x18\x05 \x01(\x05H\x04R\x04page\x88\x01\x01B\b\n" +
	"\x06_queryB\n" +
	"\n" +
	"\b_sort_byB\b\n" +
	"\x06_orderB\b\n" +
	"\x06_limitB\a\n" +
	"\x05_page\"m\n" +
	"\x12ListEventsResponse\x12$\n" +
	"\x06events\x18\x01 \x03(\v2\f.event.EventR\x06events\x121\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x11.event.PaginationR\n" +
	"pagination\"\a\n" +
	"\x05Empty\"\xfa\x01\n" +
	"\tEventZone\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x1f\n" +
	"\vlocation_id\x18\x03 \x01(\tR\n" +
	"locationId\x12\x1f\n" +
	"\vzone_number\x18\x04 \x01(\x05R\n" +
	"zoneNumber\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x14\n" +
	"\x05color\x18\x06 \x01(\tR\x05color\x12\x12\n" +
	"\x04name\x18\a \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1e\n" +
	"\vis_sold_out\x18\t \x01(\bR\tisSoldOut\"\xd7\x01\n" +
	"\x16CreateEventZoneRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1f\n" +
	"\vlocation_id\x18\x02 \x01(\tR\n" +
	"locationId\x12\x1f\n" +
	"\vzone_number\x18\x03 \x01(\x05R\n" +
	"zoneNumber\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x14\n" +
	"\x05color\x18\x05 \x01(\tR\x05color\x12\x12\n" +
	"\x04name\x18\x06 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\")\n" +
	"\x17CreateEventZoneResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x1cGetEventZoneByEventIdRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\"E\n" +
	"\x1dGetEventZoneByEventIdResponse\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.event.EventZoneR\x04list\"\x99\x03\n" +
	"\x16UpdateEventZoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\bevent_id\x18\x02 \x01(\tH\x00R\aeventId\x88\x01\x01\x12$\n" +
	"\vlocation_id\x18\x03 \x01(\tH\x01R\n" +
	"locationId\x88\x01\x01\x12$\n" +
	"\vzone_number\x18\x04 \x01(\x05H\x02R\n" +
	"zoneNumber\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x05 \x01(\x01H\x03R\x05price\x88\x01\x01\x12\x19\n" +
	"\x05color\x18\x06 \x01(\tH\x04R\x05color\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\a \x01(\tH\x05R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\b \x01(\tH\x06R\vdescription\x88\x01\x01\x12#\n" +
	"\vis_sold_out\x18\t \x01(\bH\aR\tisSoldOut\x88\x01\x01B\v\n" +
	"\t_event_idB\x0e\n" +
	"\f_location_idB\x0e\n" +
	"\f_zone_numberB\b\n" +
	"\x06_priceB\b\n" +
	"\x06_colorB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x0e\n" +
	"\f_is_sold_out\")\n" +
	"\x17UpdateEventZoneResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16DeleteEventZoneRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x9a\x05\n" +
	"\fEventService\x12D\n" +
	"\vCreateEvent\x12\x19.event.CreateEventRequest\x1a\x1a.event.CreateEventResponse\x12;\n" +
	"\bGetEvent\x12\x16.event.GetEventRequest\x1a\x17.event.GetEventResponse\x12D\n" +
	"\vUpdateEvent\x12\x19.event.UpdateEventRequest\x1a\x1a.event.UpdateEventResponse\x126\n" +
	"\vDeleteEvent\x12\x19.event.DeleteEventRequest\x1a\f.event.Empty\x12A\n" +
	"\n" +
	"ListEvents\x12\x18.event.ListEventsRequest\x1a\x19.event.ListEventsResponse\x12P\n" +
	"\x0fCreateEventZone\x12\x1d.event.CreateEventZoneRequest\x1a\x1e.event.CreateEventZoneResponse\x12b\n" +
	"\x15GetEventZoneByEventId\x12#.event.GetEventZoneByEventIdRequest\x1a$.event.GetEventZoneByEventIdResponse\x12P\n" +
	"\x0fUpdateEventZone\x12\x1d.event.UpdateEventZoneRequest\x1a\x1e.event.UpdateEventZoneResponse\x12>\n" +
	"\x0fDeleteEventZone\x12\x1d.event.DeleteEventZoneRequest\x1a\f.event.EmptyBFZDgithub.com/cp-rektmart/aconcert-microservice/pkg/proto/event;eventpbb\x06proto3"

var (
	file_event_event_proto_rawDescOnce sync.Once
	file_event_event_proto_rawDescData []byte
)

func file_event_event_proto_rawDescGZIP() []byte {
	file_event_event_proto_rawDescOnce.Do(func() {
		file_event_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_event_event_proto_rawDesc), len(file_event_event_proto_rawDesc)))
	})
	return file_event_event_proto_rawDescData
}

var file_event_event_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_event_event_proto_goTypes = []any{
	(*Event)(nil),                         // 0: event.Event
	(*CreateEventRequest)(nil),            // 1: event.CreateEventRequest
	(*CreateEventResponse)(nil),           // 2: event.CreateEventResponse
	(*GetEventRequest)(nil),               // 3: event.GetEventRequest
	(*GetEventResponse)(nil),              // 4: event.GetEventResponse
	(*UpdateEventRequest)(nil),            // 5: event.UpdateEventRequest
	(*UpdateEventResponse)(nil),           // 6: event.UpdateEventResponse
	(*DeleteEventRequest)(nil),            // 7: event.DeleteEventRequest
	(*DeleteEventResponse)(nil),           // 8: event.DeleteEventResponse
	(*Pagination)(nil),                    // 9: event.Pagination
	(*ListEventsRequest)(nil),             // 10: event.ListEventsRequest
	(*ListEventsResponse)(nil),            // 11: event.ListEventsResponse
	(*Empty)(nil),                         // 12: event.Empty
	(*EventZone)(nil),                     // 13: event.EventZone
	(*CreateEventZoneRequest)(nil),        // 14: event.CreateEventZoneRequest
	(*CreateEventZoneResponse)(nil),       // 15: event.CreateEventZoneResponse
	(*GetEventZoneByEventIdRequest)(nil),  // 16: event.GetEventZoneByEventIdRequest
	(*GetEventZoneByEventIdResponse)(nil), // 17: event.GetEventZoneByEventIdResponse
	(*UpdateEventZoneRequest)(nil),        // 18: event.UpdateEventZoneRequest
	(*UpdateEventZoneResponse)(nil),       // 19: event.UpdateEventZoneResponse
	(*DeleteEventZoneRequest)(nil),        // 20: event.DeleteEventZoneRequest
}
var file_event_event_proto_depIdxs = []int32{
	0,  // 0: event.GetEventResponse.event:type_name -> event.Event
	0,  // 1: event.ListEventsResponse.events:type_name -> event.Event
	9,  // 2: event.ListEventsResponse.pagination:type_name -> event.Pagination
	13, // 3: event.GetEventZoneByEventIdResponse.list:type_name -> event.EventZone
	1,  // 4: event.EventService.CreateEvent:input_type -> event.CreateEventRequest
	3,  // 5: event.EventService.GetEvent:input_type -> event.GetEventRequest
	5,  // 6: event.EventService.UpdateEvent:input_type -> event.UpdateEventRequest
	7,  // 7: event.EventService.DeleteEvent:input_type -> event.DeleteEventRequest
	10, // 8: event.EventService.ListEvents:input_type -> event.ListEventsRequest
	14, // 9: event.EventService.CreateEventZone:input_type -> event.CreateEventZoneRequest
	16, // 10: event.EventService.GetEventZoneByEventId:input_type -> event.GetEventZoneByEventIdRequest
	18, // 11: event.EventService.UpdateEventZone:input_type -> event.UpdateEventZoneRequest
	20, // 12: event.EventService.DeleteEventZone:input_type -> event.DeleteEventZoneRequest
	2,  // 13: event.EventService.CreateEvent:output_type -> event.CreateEventResponse
	4,  // 14: event.EventService.GetEvent:output_type -> event.GetEventResponse
	6,  // 15: event.EventService.UpdateEvent:output_type -> event.UpdateEventResponse
	12, // 16: event.EventService.DeleteEvent:output_type -> event.Empty
	11, // 17: event.EventService.ListEvents:output_type -> event.ListEventsResponse
	15, // 18: event.EventService.CreateEventZone:output_type -> event.CreateEventZoneResponse
	17, // 19: event.EventService.GetEventZoneByEventId:output_type -> event.GetEventZoneByEventIdResponse
	19, // 20: event.EventService.UpdateEventZone:output_type -> event.UpdateEventZoneResponse
	12, // 21: event.EventService.DeleteEventZone:output_type -> event.Empty
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_event_event_proto_init() }
func file_event_event_proto_init() {
	if File_event_event_proto != nil {
		return
	}
	file_event_event_proto_msgTypes[5].OneofWrappers = []any{}
	file_event_event_proto_msgTypes[10].OneofWrappers = []any{}
	file_event_event_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_event_event_proto_rawDesc), len(file_event_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_event_event_proto_goTypes,
		DependencyIndexes: file_event_event_proto_depIdxs,
		MessageInfos:      file_event_event_proto_msgTypes,
	}.Build()
	File_event_event_proto = out.File
	file_event_event_proto_goTypes = nil
	file_event_event_proto_depIdxs = nil
}
